export enum Screen {
  HOME = 'HOME',
  BIBLE = 'BIBLE',
  MANA = 'MANA',
  ENSINOS = 'ENSINOS',
  EBD = 'EBD',
  BOOKSTORE = 'BOOKSTORE',
  REFUTACAO = 'REFUTACAO',
  APOCRYPHA = 'APOCRYPHA',
  SETTINGS = 'SETTINGS',
}
