export enum Screen {
  HOME = 'HOME',
  PREACHER = 'PREACHER',
  COURSE = 'COURSE',
  BIBLE = 'BIBLE',
  MANA = 'MANA',
  DISCIPULOS = 'DISCIPULOS',
  ENSINOS = 'ENSINOS',
  EBD = 'EBD',
  BOOKSTORE = 'BOOKSTORE',
  REFUTACAO = 'REFUTACAO',
  APOCRYPHA = 'APOCRYPHA',
  SETTINGS = 'SETTINGS',
}
